version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV=dev
    env_file:
      - .env.${ENV:-dev}
    depends_on:
      - postgres
    networks:
      - jeki-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jeki-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
    volumes:
      - ./docs/swagger:/swagger
    networks:
      - jeki-network

networks:
  jeki-network:
    driver: bridge

volumes:
  postgres_data:
